name: Ultroid workflow

on:
    push:
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@main
       
       - name: Initialization
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.GH_NAME }}
           git config --global user.email ${{ secrets.GH_MAIL }}
           git config --global credential.helper store
           echo "https://${{ secrets.GH_NAME }}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
       - name: Cloning Private repo
         continue-on-error: true
         run: |
           git clone https://${{ secrets.GH_NAME }}:${{ secrets.GH_TOKEN }}@${{ secrets.PR }} PR
       - name: Running Userbot
         timeout-minutes: 350
         continue-on-error: true
         run: |
           pip3 --no-cache-dir install telethon-tgcrypto
           sudo sh ultroid.sh
       - name: Loop
         continue-on-error: true
         run: |
              git clone https://github.com/${{ secrets.GH_REPO }} loop
              cd loop || exit 1
              echo $(TZ='${{ secrets.TZ }}' date) >> loop.txt
              git add loop.txt
              git commit -m "Workflow : Loop $(TZ='${{ secrets.TZ }}' date)"
              git push -q https://${{ secrets.GH_TOKEN }}@github.com/${{ secrets.GH_REPO }} HEAD:main
